name: Clang-Tidy

on:
  pull_request:

env:
  CONAN_SERVER_USER: ciw
  CONAN_SERVER_PASSWORD: VZKhzh2v5nCnijAS3A8R
  TARGET: Debug

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up clang-tidy
      run: sudo apt-get install clang-tidy

    - name: Run clang-tidy
      run: |
        cd build
        cmake ..
        make
        clang-tidy -p=build source/**/*.cpp
