name: Clang-Tidy

on: push

env:
  CONAN_SERVER_USER: ciw
  CONAN_SERVER_PASSWORD: VZKhzh2v5nCnijAS3A8R
  TARGET: Debug

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up clang-tidy
      run: sudo apt-get install clang-tidy

    - name: Run clang-tidy
      run: |
        sudo apt install python3-pip
        pip3 install conan
        conan --profile detect
        conan remote add doc https://monkfish-app-qfnky.ondigitalocean.app
        conan user ciw -r doc -p VZKhzh2v5nCnijAS3A8R
        conan install . --build missing
        conan build .
        cd build
        cmake ..
        make
        clang-tidy -p=build source/**/*.cpp
