name: Clang-Tidy

on: push

env:
  CONAN_SERVER_USER: ciw
  CONAN_SERVER_PASSWORD: VZKhzh2v5nCnijAS3A8R
  TARGET: Debug

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up python
          id: setup-python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - run: pip install conan

        - name: Setup cmake
          uses: jwlawson/actions-setup-cmake@v1.13
          with:
              cmake-version: '3.16.x'

        - name: Cache conan files
          id: cached-conan-files
          uses: actions/cache@v3
          with:
            path: "~/.conan2"
            key: ${{ runner.os }}-${{ hashFiles('conan.lock') }}

        - name: Create conan profile
          if: steps.cached-conan-files.outputs.cache-hit != 'true'
          run: conan profile detect

        - name: Add conan remote
          if: steps.cached-conan-files.outputs.cache-hit != 'true'
          run: conan remote add coaler $CONAN_SERVER_URL

        - name: Login into conan server
          if: steps.cached-conan-files.outputs.cache-hit != 'true'
          run: conan remote login coaler $CONAN_SERVER_USER --password $CONAN_SERVER_PASSWORD

        - name: Build
          run: conan build .

        - name: Clang-Tidy
          run:  clang-tidy -p=build source/**/*.cpp