name: Clang-Tidy

on:
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.h'

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up clang-tidy
      run: sudo apt-get install clang-tidy

    - name: Run clang-tidy
      run: |
        mkdir build
        cd build
        cmake ..
        make
        clang-tidy -p=build source/**/*.cpp
